### ISSUE TITLE
Permanent "wait" state after doing five annotations

### ISSUE THREAD

**Issue by yogaraptor** [zooniverse/old-weather#94] opened 2016-06-02 16:13 UTC
After annotating five pages for a ship, a sixth page will not get loaded. The loading spinner appears but nothing is ever loaded.

This appears to be because subjects are [fetched using the "queued" sort](https://github.com/zooniverse/old-weather/blob/master/app/modules/transcribe/scripts/init.js#L423), which is only returning (just for these users, possibly? It does for me, at any rate) five subjects, even though a `page_size` of 20 is requested.

When the user has done five annotations, the front end realises there are no more in the local store and goes to fetch the next page of subjects. Panoptes returns an empty collection (makes sense - if there were only five in the first page when 20 were requested, the second page won't have any). The frontend doesn't seem equipped to handle this and simply does nothing. 

If the subject fetch sort is set to a "basic" sort, e.g. `created_at`, then 20 subjects are returned for each page. I'm not clear why the frontend is using the `queued` sort, which as I understand it is reserved for manually created queues of subjects targeted at a particular user.

Regardless of which sort is used, the frontend should use the pagination meta on the JSON-API response to check whether there is a "next" page of subjects - users may reach the "end" of a subject set at some point, and currently the frontend will display the same "wait" state at that point.

**Comment by yogaraptor** [comment] 2016-06-02 16:29
After discussion with @rogerhutchings, it sounds like we can just remove the `queued` sort. We might want to use `cellect` initially to ensure users don't get subjects they've already seen until they've annotated every page in a subject set.

**Comment by camallen** [comment] 2016-06-03 08:34
@itsravenous firstly that empty data response is either a bug in the API or a misconfigured request in the client..we should debug this. 

Second the queued sort is a slight misnomer here (looking forward we'll probably replace that with something else). That param is an override to the normal subjects end point to activate the subject selection smarts int he API. The smarts do a few things:
1. Select subjects based on the configured property for the workflow, default=random, priority and if requested by subject set
2. Only select data that user hasn't not seen
3. Only select data that is not retired

If you don't' use this end point override then you'll just get the standard first page into the available scope of that workflow / user_id combo. It'll be db natural sort order as i don't think we've added any other sort orders on that end point.

**Comment by camallen** [comment] 2016-06-03 08:35
Also i think the problem is the page param [here](https://github.com/zooniverse/old-weather/blob/master/app/modules/transcribe/scripts/init.js#L425), you don't need a page param on there - that selection point will return the relevant page size for you and you only want it's first page.

**Comment by yogaraptor** [comment] 2016-06-03 10:06
@camallen thanks for clarifying `queued`! Still not sure why the endpoint only returns five subjects though (when removing `queued` gives you 20). I'd guess that it's because they are the only unretired subjects, but this is a long-known issue and present on production and staging, so that doesn't sound right...

Also not clear on why you'd only want the first page - if there are more available subjects than `page_size` you want the next page once you're done with those subjects don't you?

**Comment by camallen** [comment] 2016-06-03 10:43
I am pretty sure this is expected behaviour, it'll be returning you data you haven't seen / isn't retired and it may be 1 or more). If you've seen all the data it'll just get retired data you haven't seen and then fallback to just anything (but it will mark them all properly).

Please remove the page param entirely form the request...they should not be there at all since the API will be returning you the specific allocation of data, e.g. there are 20 subjects in a set, you've seen 5 of them, 5 are retired, you then ask for more with page_size = 10 and the api returns the remaining 10 you haven't seen. If you then page=2 into that it'll be empty since there are only 10 subjects you haven't seen. This was known issue with annotate...basically use the "queued" selection end point to activate the subject selection api smarts and then specify a page size...the API will do it's best to return you the page size but it's dependent on the set size and what is seen / retired.

Can you provide the workflow, user_id and subject set (if present) for the selection end point? I'll look into it to make sure it's working.

**Comment by yogaraptor** [comment] 2016-06-03 10:51
I'm with you now! `workflow_id=886&subject_set_id=2493`

**Comment by camallen** [comment] 2016-06-03 15:11
@itsravenous this is a bug on grouped selection - fix coming soon.

**Comment by camallen** [comment] 2016-06-15 09:11
@itsravenous this should be fixed for you now.

**Comment by yogaraptor** [comment] 2016-06-17 10:18
Confirmed - thankyou! #99 fixes the rest of this issue, will close this once merged.

**Closed as completed** 2016-06-22 18:16 UTC
